name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - name: Run ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"
